import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { QrcodesContextProvider } from '@/contexts/QrcodesContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gerador de qrcode / Inicio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QrcodesContextProvider>{children}</QrcodesContextProvider>
      </body>
    </html>
  )
}
